### ISSUE TITLE
Crash in websocket

### ISSUE THREAD

**Issue by kjk** [ravendb/ravendb-go-client#104]
Flaky, happened once running all tests locally on Windows:
```
WebSocketChangesProcessor.processMessages() ReadJSON() failed with read tcp 127.0.0.1:10957->127.0.0.1:10927: use of closed network connection
DatabaseChanges.send: WriteJSON() failed with write tcp 127.0.0.1:10957->127.0.0.1:10927: use of closed network connection
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x880e1f]

goroutine 5759 [running]:
github.com/gorilla/websocket.(*Conn).prepWrite(0x0, 0x1, 0x40, 0x2030002)
        C:/Users/kjk/go/pkg/mod/github.com/gorilla/websocket@v1.4.0/conn.go:458 +0x4f
github.com/gorilla/websocket.(*Conn).NextWriter(0x0, 0x1, 0xc0002f01c0, 0x20, 0x28, 0xc000941d10)
        C:/Users/kjk/go/pkg/mod/github.com/gorilla/websocket@v1.4.0/conn.go:494 +0x65
github.com/gorilla/websocket.(*Conn).WriteJSON(0x0, 0xb50c40, 0xc000941d10, 0xc000941d10, 0x1)
        C:/Users/kjk/go/pkg/mod/github.com/gorilla/websocket@v1.4.0/json.go:24 +0x61
github.com/ravendb/ravendb-go-client.(*DatabaseChanges).send(0xc0002f0180, 0xbb230f, 0xd, 0x0, 0x0, 0xc00077f450, 0xaf5d00)
        C:/Users/kjk/src/ravendb-go-client/database_changes.go:432 +0x20a
github.com/ravendb/ravendb-go-client.(*DatabaseChanges).getOrAddConnectionState.func2()
        C:/Users/kjk/src/ravendb-go-client/database_changes.go:392 +0x6d
github.com/ravendb/ravendb-go-client.(*DatabaseChanges).doWork(0xc0002f0180, 0x0, 0x48fd36)
        C:/Users/kjk/src/ravendb-go-client/database_changes.go:514 +0x6aa
github.com/ravendb/ravendb-go-client.NewDatabaseChanges.func1(0xc0002f0180)
        C:/Users/kjk/src/ravendb-go-client/database_changes.go:61 +0x44
created by github.com/ravendb/ravendb-go-client.NewDatabaseChanges
        C:/Users/kjk/src/ravendb-go-client/database_changes.go:60 +0x4a8
FAIL    github.com/ravendb/ravendb-go-client/tests      255.877s
```

**Comment by kjk** [comment]
Maybe related (from https://travis-ci.org/ravendb/ravendb-go-client/builds/488014161):
```
databaseChanges.send: WriteJSON() failed with write tcp 127.0.0.1:34894->127.0.0.1:40295: use of closed network connection
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8863e8]
goroutine 225 [running]:
github.com/gorilla/websocket.(*Conn).beginMessage(0x0, 0xc0004546f0, 0x1, 0x4274a0, 0x0)
	/home/travis/gopath/src/github.com/gorilla/websocket/conn.go:459 +0x48
github.com/gorilla/websocket.(*Conn).NextWriter(0x0, 0x1, 0x465afa, 0x20, 0x28, 0xc0004546c0)
	/home/travis/gopath/src/github.com/gorilla/websocket/conn.go:500 +0xb5
github.com/gorilla/websocket.(*Conn).WriteJSON(0x0, 0xbae020, 0xc0004546c0, 0xc0004546c0, 0x1)
	/home/travis/gopath/src/github.com/gorilla/websocket/json.go:24 +0x5a
github.com/ravendb/ravendb-go-client.(*databaseChanges).send(0xc000204000, 0xc149ac, 0xd, 0x0, 0x0, 0xc0001ee640, 0xb6f400)
	/home/travis/gopath/src/github.com/ravendb/ravendb-go-client/database_changes.go:408 +0x173
github.com/ravendb/ravendb-go-client.(*databaseChanges).getOrAddConnectionState.func2()
	/home/travis/gopath/src/github.com/ravendb/ravendb-go-client/database_changes.go:368 +0xb4
github.com/ravendb/ravendb-go-client.(*databaseChanges).doWork(0xc000204000, 0x1, 0x4)
	/home/travis/gopath/src/github.com/ravendb/ravendb-go-client/database_changes.go:484 +0x720
github.com/ravendb/ravendb-go-client.newDatabaseChanges.func1(0xc000204000)
	/home/travis/gopath/src/github.com/ravendb/ravendb-go-client/database_changes.go:62 +0x55
created by github.com/ravendb/ravendb-go-client.newDatabaseChanges
	/home/travis/gopath/src/github.com/ravendb/ravendb-go-client/database_changes.go:61 +0x368	````
