### ISSUE TITLE
struct with pointer to struct cannot be deserialized

### ISSUE THREAD

**Issue by kjk** [ravendb/ravendb-go-client#116]
E.g. in `loadEmployee()` in `examples\main.go`

```
panic: reflect: call of reflect.Value.Set on zero Value

goroutine 1 [running]:
reflect.flag.mustBeExported(0x0)
        C:/Go/src/reflect/value.go:215 +0xb4
reflect.Value.Set(0x6800c0, 0xc000078248, 0x196, 0x0, 0x0, 0x0)
        C:/Go/src/reflect/value.go:1398 +0x47
github.com/ravendb/ravendb-go-client.setInterfaceToValue(0x67a1c0, 0xc000078248, 0x0, 0x0)
        C:/Users/kjk/src/ravendb-go-client/entity_to_json.go:62 +0x1ac
github.com/ravendb/ravendb-go-client.(*entityToJSON).ConvertToEntity2(0xc00013a410, 0x67a1c0, 0xc000078248, 0xc000170293, 0xd, 0xc00014c240)
        C:/Users/kjk/src/ravendb-go-client/entity_to_json.go:90 +0x164
github.com/ravendb/ravendb-go-client.(*InMemoryDocumentSessionOperations).TrackEntity(0xc000040480, 0x67a1c0, 0xc000078248, 0xc000170293, 0xd, 0xc00014c240, 0xc00014c2a0, 0xc000170300, 0xd, 0xc0001c43c8)
        C:/Users/kjk/src/ravendb-go-client/in_memory_document_session_operations.go:400 +0x19e
github.com/ravendb/ravendb-go-client.(*InMemoryDocumentSessionOperations).TrackEntityInDocumentInfo(0xc000040480, 0x67a1c0, 0xc000078248, 0xc0001aa230, 0xc0001c43c8, 0xc000182300)
        C:/Users/kjk/src/ravendb-go-client/in_memory_document_session_operations.go:382 +0x77
github.com/ravendb/ravendb-go-client.(*LoadOperation).getDocumentWithID(0xc000075eb0, 0x67a1c0, 0xc000078248, 0x700dc9, 0xd, 0x0, 0xc000172180)
        C:/Users/kjk/src/ravendb-go-client/load_operation.go:102 +0xc9
github.com/ravendb/ravendb-go-client.(*LoadOperation).getDocument(0xc000075eb0, 0x67a1c0, 0xc000078248, 0xc000051de0, 0x0)
        C:/Users/kjk/src/ravendb-go-client/load_operation.go:80 +0x62
github.com/ravendb/ravendb-go-client.(*DocumentSession).Load(0xc000138960, 0x67a1c0, 0xc000078248, 0x700dc9, 0xd, 0x0, 0x405477)
        C:/Users/kjk/src/ravendb-go-client/document_session.go:376 +0x153
main.loadEmployee()
        C:/Users/kjk/src/ravendb-go-client/examples/main.go:49 +0x143
```

**Comment by kjk** [comment]
The issue is that built-in json decoding will fail if the struct field we're decoding is not compatible with the json value we're decoding.

In this particular case, `Employee` struct has field `ReportsTo  *Employee` but the json returned from the server sends a string (which is an id of the entity).

To fix that I have to write a custom json decoder.

**Comment by ayende** [comment]
Take into account that this is actually something that we aren't supporting anywhere.
Your model isn't supposed to have a `ReportsTo *Employee`, it should be `ReportsTo string`

**Comment by kjk** [comment]
There are 2 issues:

1. Not crashing due to type mismatch.

2. Auto-decoding ids as structs (I assume only if using includes).

The scope of this issue is only not crashing.

But it does bring a question: what should happen during a type mismatch e.g. when struct defines an int and the json returned from the server has e.g. a string.

Should this be an error or should we silently drop mismatched entries?

**Comment by ayende** [comment]
A type mismatch should behave like a normal type mismatch in the language.
In C#, that would typically throw.

**Comment by kjk** [comment]
Thanks for the information, that makes things simpler.
