### ISSUE TITLE
allow providing http.Client to RequestExecutor

### ISSUE THREAD

**Issue by kjk** [ravendb/ravendb-go-client#56]
Either pass `[]tls.Certificate` directly or allow over-riding creation of http client, which is most flexible and allows creating https client.

**Comment by kjk** [comment]
Also implement comments from https://github.com/ravendb/ravendb-go-client/pull/55#pullrequestreview-155921276: generate certs on demand

It'll make testing on mac more cumbersome (because there's no command-line way of importing a ca cert as root certificate and server won't trust the certificate otherwise).

**Comment by ayende** [comment]
Why won't the server trust the cert?

**Comment by kjk** [comment]
This is the error when using a cert signed with ca that isn't in mac's root store:
```
2018-09-18T18:40:14.8966480Z, 3, Information, ServerStore, Raven.Server.ServerWide.ServerStore, Tried to send message to leader, retrying, EXCEPTION: Raven.Client.Exceptions.RavenException: System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception. ---> System.Security.Authentication.AuthenticationException: The remote certificate is invalid according to the validation procedure.
   at System.Net.Security.SslState.StartSendAuthResetSignal(ProtocolToken message, AsyncProtocolRequest asyncRequest, ExceptionDispatchInfo exception)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessReceivedBlob(Byte[] buffer, Int32 count, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.StartReadFrame(Byte[] buffer, Int32 readBytes, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.PartialFrameCallback(AsyncProtocolRequest asyncRequest)
--- End of stack trace from previous location where exception was thrown ---
   at System.Net.Security.SslState.ThrowIfExceptional()
   at System.Net.Security.SslState.InternalEndProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Net.Security.SslState.EndProcessAuthentication(IAsyncResult result)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.<>c.<AuthenticateAsClientAsync>b__47_1(IAsyncResult iar)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
```

On Linux this can be fixed from cmd-line with:
```
sudo cp ca.crt /usr/local/share/ca-certificates/ca.crt
sudo update-ca-certificates
```

On Mac the only way I know is to manually add it using Keychain Access app. On a practical level that precludes automated testing on mac that regenerates certs on every test run.

**Comment by ayende** [comment]
@iftahbe Can you take a look?

**Comment by kjk** [comment]
The Go Way is to allow users to provide custom http.Client. That way they can control all aspects of http connection (timeouts, proxies etc.) as well as establishing HTTPS connections, which would make KeyStore redundant.

**Comment by kjk** [comment]
We ended up with passing certificate info externally.

There is a hook HTTPClientPostProcessor for tweaking http.Client after it was created (e.g. for logging, as used by tests).
