### ISSUE TITLE
panic: runtime error: hash of unhashable type map[string]interface {}

### ISSUE THREAD

**Issue by Generalomosco** [ravendb/ravendb-go-client#60]
I always got this below error when i try to insert `interfac`e to my database.
Here is my code:

```
obj := map[string]interface{}{}
    obj["foo1"] = "bar1"
  err = session.StoreWithID(obj, "myKeyId")

```
Even when still try this:

 ```
obj := map[string]interface{}{}
    obj["foo1"] = "bar1"
   doc, _ := ravendb.MakeStructFromJSONMap(reflect.TypeOf(obj), obj)
  err = session.StoreWithID(doc, "myKeyId")
```
Only the thing that worked is Struct and i don't want to use struct, i want to use dynamic json interface

```
panic: runtime error: hash of unhashable type map[string]interface {}

goroutine 1 [running]:
github.com/bxcodec/go-clean-arch-grpc/vendor/github.com/ravendb/ravendb-go-client.(*InMemoryDocumentSessionOperations).StoreEntityInUnitOfWork(0xc0000d8c60, 0xb5fe35, 0x2, 0xa74640, 0xc00010cd50, 0x0, 0xc00010cd80, 0x0)
        /var/www/vhosts/domain.com/_golangPath01/src/src/github.com/bxcodec/go-clean-arch-grpc/vendor/github.com/ravendb/ravendb-go-client/in_memory_document_session_operations.go:590 +0x14c
github.com/bxcodec/go-clean-arch-grpc/vendor/github.com/ravendb/ravendb-go-client.(*InMemoryDocumentSessionOperations).storeInternal(0xc0000d8c60, 0xa74640, 0xc00010cd50, 0x0, 0xb5fe35, 0x2, 0x0, 0x0, 0x0)
        /var/www/vhosts/domain.com/_golangPath01/src/src/github.com/bxcodec/go-clean-arch-grpc/vendor/github.com/ravendb/ravendb-go-client/in_memory_document_session_operations.go:572 +0x455
github.com/bxcodec/go-clean-arch-grpc/vendor/github.com/ravendb/ravendb-go-client.(*InMemoryDocumentSessionOperations).StoreWithID(0xc0000d8c60, 0xa74640, 0xc00010cd50, 0xb5fe35, 0x2, 0x0, 0x0)
        /var/www/vhosts/domain.com/_golangPath01/src/src/github.com/bxcodec/go-clean-arch-grpc/vendor/github.com/ravendb/ravendb-go-client/in_memory_document_session_operations.go:500 +0x65
main.main()
        /var/www/vhosts/domain.com/_golangPath01/src/src/github.com/bxcodec/go-clean-arch-grpc/main.go:57 +0x2f6
exit status 2
```

**Comment by Generalomosco** [comment]
Finally i succeeded with this..
 type Body struct {
    Doc interface{}
}
  u := &Body{Doc:obj}
  err = session.StoreWithID(u, "gg")

**Comment by kjk** [comment]
The library is still in beta stage and currently not being able to store maps is a limitation.

**Comment by kjk** [comment]
merge with #105
