### ISSUE TITLE
include not working

### ISSUE THREAD

**Issue by kjk** [ravendb/ravendb-go-client#63]
in https://github.com/ravendb/ravendb-go-client/blob/master/examples/read/main.go#L88
```
	// TODO: not supported yet
	if false {
		session, err := store.OpenSession()
		panicIfErr(err)
		session.Include("employee")
		var o *Order
		err = session.Load(&o, "orders/827-A")
		panicIfErr(err)
		fmt.Printf("order: %#v\n", o)
	}
```
This panics with:
```
panic: reflect: call of reflect.Value.Set on zero Value

goroutine 1 [running]:
reflect.flag.mustBeExported(0x0)
	/usr/local/Cellar/go/1.11.1/libexec/src/reflect/value.go:215 +0xad
reflect.Value.Set(0x1288ac0, 0xc0000aa308, 0x196, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.11.1/libexec/src/reflect/value.go:1398 +0x40
github.com/ravendb/ravendb-go-client.setInterfaceToValue(0x12830c0, 0xc0000aa308, 0x0, 0x0)
	/Users/kjk/src/ravendb-go-client/entity_to_json.go:62 +0x1a5
github.com/ravendb/ravendb-go-client.(*EntityToJson).ConvertToEntity2(0xc00016ed20, 0x12830c0, 0xc0000aa308, 0xc000016570, 0xc, 0xc0001aa540)
	/Users/kjk/src/ravendb-go-client/entity_to_json.go:74 +0x146
github.com/ravendb/ravendb-go-client.(*InMemoryDocumentSessionOperations).TrackEntity(0xc000086c00, 0x12830c0, 0xc0000aa308, 0xc000016570, 0xc, 0xc0001aa540, 0xc0001aa5d0, 0xc000099e00, 0xc, 0xc50000c0001aa500)
	/Users/kjk/src/ravendb-go-client/in_memory_document_session_operations.go:360 +0x4e2
github.com/ravendb/ravendb-go-client.(*InMemoryDocumentSessionOperations).TrackEntityInDocumentInfo(0xc000086c00, 0x12830c0, 0xc0000aa308, 0xc000172a80, 0xc000099e98, 0x124e9f8)
	/Users/kjk/src/ravendb-go-client/in_memory_document_session_operations.go:314 +0x70
github.com/ravendb/ravendb-go-client.(*LoadOperation).getDocumentWithID(0xc0000ddea0, 0x12830c0, 0xc0000aa308, 0x130ae1d, 0xc, 0xc00000c520, 0xc000172a80)
	/Users/kjk/src/ravendb-go-client/load_operation.go:101 +0xd4
github.com/ravendb/ravendb-go-client.(*LoadOperation).getDocument(0xc0000ddea0, 0x12830c0, 0xc0000aa308, 0xc000246348, 0x0)
	/Users/kjk/src/ravendb-go-client/load_operation.go:79 +0x5b
github.com/ravendb/ravendb-go-client.(*DocumentSession).Load(0xc000166fc0, 0x12830c0, 0xc0000aa308, 0x130ae1d, 0xc, 0xc00016ed30, 0x0)
	/Users/kjk/src/ravendb-go-client/document_session.go:278 +0xeb
main.main()
	/Users/kjk/src/ravendb-go-client/examples/read/main.go:92 +0x252
```

Probably need to create a pointer value before assigning to it.

**Comment by ayende** [comment]
```
session.Include("employee")
var o *Order
err = session.Load(&o, "orders/827-A")
```

This is very strange.
What I would expect is:

```
var o *Order
err = session.Include("employee").Load(&o, "orders/827-A")
```

**Comment by kjk** [comment]
Ahh, I see.

I fixed the example.

Still errors out with:
```
panic: type of result should be pointer-to-struct but is **main.Order

goroutine 1 [running]:
main.panicIfErr(0x135a980, 0xc000010ad0)
	/Users/kjk/src/ravendb-go-client/examples/read/main.go:70 +0x86
main.main()
	/Users/kjk/src/ravendb-go-client/examples/read/main.go:94 +0x2ca
```
