### ISSUE TITLE
Figure out why query_queryWithDuration is flaky

### ISSUE THREAD

**Issue by kjk** [ravendb/ravendb-go-client#77]
Sometimes (but not always) query_queryWithDuration fails because the server marks index as errored.

Full log of failed run: https://gist.github.com/kjk/b75f3572e09403ba9bb52467ab2f63b7

The error in question:
```
{
  "Error": "System.InvalidOperationException: Index 'OrderTime' is marked as errored. Index OrderTime is invalid, out of 3 map attempts, 3 has failed. Error rate of 100% exceeds allowed 15% error rate
   at Raven.Server.Documents.Indexes.Index.ThrowMarkedAsError(String errorStateReason) in C:\\Builds\\RavenDB-Stable-4.1\\src\\Raven.Server\\Documents\\Indexes\\Index.cs:line 2495
   at Raven.Server.Documents.Indexes.Index.QueryInternal[TQueryResult](TQueryResult resultToFill, IndexQueryServerSide query, DocumentsOperationContext documentsContext, OperationCancelToken token) in C:\\Builds\\RavenDB-Stable-4.1\\src\\Raven.Server\\Documents\\Indexes\\Index.cs:line 2024
   at Raven.Server.Documents.Indexes.Index.Query(IndexQueryServerSide query, DocumentsOperationContext documentsContext, OperationCancelToken token) in C:\\Builds\\RavenDB-Stable-4.1\\src\\Raven.Server\\Documents\\Indexes\\Index.cs:line 2017
   at Raven.Server.Documents.Queries.QueryRunner.ExecuteQuery(IndexQueryServerSide query, DocumentsOperationContext documentsContext, Nullable`1 existingResultEtag, OperationCancelToken token) in C:\\Builds\\RavenDB-Stable-4.1\\src\\Raven.Server\\Documents\\Queries\\QueryRunner.cs:line 69
   at Raven.Server.Documents.Handlers.QueriesHandler.Query(DocumentsOperationContext context, OperationCancelToken token, RequestTimeTracker tracker, HttpMethod method) in C:\\Builds\\RavenDB-Stable-4.1\\src\\Raven.Server\\Documents\\Handlers\\QueriesHandler.cs:line 110
   at Raven.Server.Documents.Handlers.QueriesHandler.HandleQuery(HttpMethod httpMethod) in C:\\Builds\\RavenDB-Stable-4.1\\src\\Raven.Server\\Documents\\Handlers\\QueriesHandler.cs:line 56
   at Raven.Server.Routing.RequestRouter.HandlePath(HttpContext context, String method, String path) in C:\\Builds\\RavenDB-Stable-4.1\\src\\Raven.Server\\Routing\\RequestRouter.cs:line 125
   at Raven.Server.RavenServerStartup.RequestHandler(HttpContext context) in C:\\Builds\\RavenDB-Stable-4.1\\src\\Raven.Server\\RavenServerStartup.cs:line 163",
  "Message": "Index 'OrderTime' is marked as errored. Index OrderTime is invalid, out of 3 map attempts, 3 has failed. Error rate of 100% exceeds allowed 15% error rate",
  "Type": "System.InvalidOperationException",
  "Url": "/databases/test_db_1/queries?queryHash=de187248af5ee5f201d56f747c4a1672"
}
```

**Comment by kjk** [comment]
This is Go formatting of `time.Time` in UTC format in standard Go JSON library. There is no way to change formatting in standard JSON library.

One option is to change the server to accept this format (I assume that "662877Z" is equivalent to "6628770Z").

Another option is to document that for this to work people should use `ravendb.Time`.

Another option is to write custom JSON marshaller that will handle `time.Time` correctly (more realistically: fork existing marshaller as there are already many libraries out there).
